/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ex1;

/**
 *
 * @author teclab
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMnArquivo = new javax.swing.JMenu();
        jItemSair = new javax.swing.JMenuItem();
        jMnExemplos = new javax.swing.JMenu();
        jMnEx8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto Interface Gráfica");
        setResizable(false);

        jMnArquivo.setText("Arquivo");
        jMnArquivo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.CTRL_MASK));
        jItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-excluir-24.png"))); // NOI18N
        jItemSair.setText("Sair");
        jItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemSairActionPerformed(evt);
            }
        });
        jMnArquivo.add(jItemSair);

        jMenuBar1.add(jMnArquivo);

        jMnExemplos.setText("Exemplos");
        jMnExemplos.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jMnEx8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        jMnEx8.setText("Exemplo 8.3");
        jMnEx8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnEx8ActionPerformed(evt);
            }
        });
        jMnExemplos.add(jMnEx8);

        jMenuBar1.add(jMnExemplos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jItemSairActionPerformed

    private void jMnEx8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnEx8ActionPerformed
        Exemplo3 exemplo3 = new Exemplo3();
        exemplo3.setVisible(true);
    }//GEN-LAST:event_jMnEx8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jItemSair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMnArquivo;
    private javax.swing.JMenuItem jMnEx8;
    private javax.swing.JMenu jMnExemplos;
    // End of variables declaration//GEN-END:variables
}
